---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2
inputs:
  - name: vs-pcf-pipelines 

params:
  ERT_DOMAIN:
  OPSMAN_USER:
  OPSMAN_PASSWORD:

run:
  path: vs-pcf-pipelines/install-pcf/aws/tasks/config-opsman/task.sh
