---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: "rjain/buildbox"

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  OPSMAN_URI:
  SINGLETON_JOB_AZ:
  OTHER_JOB_AZS:
  NETWORK_NAME:
  ERRANDS_TO_DISABLE:
  ERRANDS_TO_WHENCHANGED:
  PREDELETE_ERRANDS_TO_DISABLE:

inputs:
  - name: vs-pcf-pipelines
  - name: tool-om

run:
  path: vs-pcf-pipelines/tasks/config-spring-cloud/task.sh
