---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

inputs:
- name: pcf-pipelines

params:
  OPSMAN_URI:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  EXTERNAL_NETWORK:
  INFRA_NETWORK:
  ERT_NETWORK:
  SERVICES_NETWORK:
  DYNAMIC_SERVICES_NETWORK:
  OS_KEYPAIR_NAME:
  SECURITY_GROUP:
  ADMIN_ROUTER:
  OPSMAN_FLOATING_IP:
  OPSMAN_VM_NAME:
  OPENSTACK_CA_CERT:
  OS_PROJECT_ID:
  OS_REGION_NAME:
  OS_USER_DOMAIN_NAME:
  OS_PROJECT_NAME:
  OS_IDENTITY_API_VERSION:
  OS_PASSWORD:
  OS_AUTH_URL:
  OS_USERNAME:
  OS_INTERFACE:

run:
  path: pcf-pipelines/install-pcf/openstack/tasks/wipe-env/task.sh
