---

platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

params:
  GOVC_INSECURE:
  GOVC_URL:
  GOVC_USERNAME:
  GOVC_PASSWORD:
  GOVC_DATACENTER:
  GOVC_DATASTORE:
  GOVC_HOST:
  GOVC_RESOURCE_POOL:
  OPS_MGR_SSH_PWD:
  OM_NTP_SERVERS:
  OM_DNS_SERVERS:
  OM_GATEWAY:
  OM_NETMASK:
  OM_IP:
  OM_VM_NETWORK:
  OM_VM_NAME:
  OM_DISK_TYPE:
  OM_VM_POWER_STATE:
  OM_VM_FOLDER:


inputs:
  - name: pivnet-opsman-product
  - name: pcf-pipelines

run:
  path: pcf-pipelines/install-pcf/vsphere/tasks/import-opsman/task.sh
