---

platform: linux

image_resource:
  type: docker-image
  source: {repository: ubuntu}

params:
  OPSPW:
  OPSMANIP:
  OPSMAN_URI:
  OPSMAN_PASSPHRASE:        

inputs:
  - name: vs-pcf-pipelines

run:
  path: vs-pcf-pipelines/tasks/config-opsman-timeout/task.sh
