---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

inputs:
- name: pcf-pipelines
- name: ops-manager

params:
  EXTERNAL_NETWORK:
  INFRA_NETWORK:
  OPENSTACK_CA_CERT:
  OS_PROJECT_ID:
  OS_REGION_NAME:
  OS_USER_DOMAIN_NAME:
  OS_PROJECT_NAME:
  OS_IDENTITY_API_VERSION:
  OS_PASSWORD:
  OS_AUTH_URL:
  OS_USERNAME:
  OPENSTACK_CA_CERT:
  OS_INTERFACE:
  OPSMAN_IMAGE:
  SECURITY_GROUP:
  OPSMAN_KEY:
  OPSMAN_FLAVOR:
  OPSMAN_VM_NAME:
  OPSMAN_FLOATING_IP:

run:
  path: pcf-pipelines/install-pcf/openstack/tasks/deploy-opsman/task.sh
